name: la_barber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.2
  firebase_database: ^10.2.4
  cached_network_image: ^3.2.0
  validatorless: ^1.2.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  firebase_messaging: ^14.0.1
  cupertino_icons: ^1.0.2
  brasil_fields: ^1.14.3
  url_launcher: ^6.1.12
  dropdown_button2: ^2.1.4
  top_snackbar_flutter: ^3.1.0
  table_calendar: ^3.1.0
  loading_animation_widget: 
    git:
      url: https://github.com/caneto/loading_animation_widget.git
  equatable: ^2.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  currency_text_input_formatter: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: dw_barbershop_icons
      fonts:
        - asset: assets/fonts/dw_barbershop_icons.ttf