import 'package:la_barber/features/admin/barber/repository/models/barber_model.dart';
import 'package:la_barber/features/admin/barbershop/repository/models/barbershop_model.dart';
import 'package:la_barber/features/admin/servicos/repository/models/servico_model.dart';
import 'package:la_barber/features/common/auth/model/user_model.dart';

class Mocks {
  static final List<BarbershopModel> companies = [
    BarbershopModel(
      id: 1,
      name: 'Penha',
      address: 'Rua do João, 123',
      phone: '123456789',
      email: '',
      logo: '',
      website: '',
      description: '',
    ),
    BarbershopModel(
      id: 2,
      name: 'Centro',
      address: 'Rua do João, 123',
      phone: '123456789',
      email: '',
      logo: '',
      website: '',
      description: '',
    ),
    BarbershopModel(
      id: 3,
      name: 'Perifa',
      address: 'Rua do João, 123',
      phone: '123456789',
      email: '',
      logo: '',
      website: '',
      description: '',
    ),
  ];

  static final List<UserModel> userBarbers = [
    UserModel(
      name: 'João',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
    UserModel(
      name: 'Mario',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
    UserModel(
      name: 'Que Mario?',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
    UserModel(
      name: 'Que Mario?',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
    UserModel(
      name: 'Que Mario?',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
    UserModel(
      name: 'Que Mario?',
      userType: UserType.barber,
      token: '123',
      refreshToken: '123',
      credentialId: 1,
    ),
  ];

  static List<BarberModel> barberList = [
    BarberModel(
      username: 'john_barber',
      email: 'john.barber@example.com',
      password: 'password123',
      name: 'John Barber',
      city: 'São Paulo',
      state: 'SP',
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apt 45',
      zipCode: '01001-000',
      commissioned: true,
      barberUnitId: 1,
      isManager: true,
    ),
    BarberModel(
      username: 'jane_doe',
      email: 'jane.doe@example.com',
      password: 'securePass456',
      name: 'Jane Doe',
      city: 'Rio de Janeiro',
      state: 'RJ',
      street: 'Avenida Atlântica',
      number: '789',
      complement: 'Sala 100',
      zipCode: '22021-000',
      commissioned: false,
      barberUnitId: 2,
      isManager: false,
    ),
    BarberModel(
      username: 'alex_hair',
      email: 'alex.hair@example.com',
      password: 'haircut789',
      name: 'Alex Hair',
      city: 'Belo Horizonte',
      state: 'MG',
      street: 'Rua do Comércio',
      number: '456',
      complement: null,
      zipCode: '30110-000',
      commissioned: true,
      barberUnitId: 3,
      isManager: false,
    ),
    BarberModel(
      username: 'chris_style',
      email: 'chris.style@example.com',
      password: 'stylePass321',
      name: 'Chris Style',
      city: 'Curitiba',
      state: 'PR',
      street: 'Avenida das Américas',
      number: '321',
      complement: 'Loja 2',
      zipCode: '80050-000',
      commissioned: true,
      barberUnitId: 4,
      isManager: true,
    ),
    BarberModel(
      username: 'samuel_cuts',
      email: 'samuel.cuts@example.com',
      password: 'cuts1234',
      name: 'Samuel Cuts',
      city: 'Porto Alegre',
      state: 'RS',
      street: 'Rua das Palmeiras',
      number: '654',
      complement: 'Bloco B',
      zipCode: '90040-000',
      commissioned: false,
      barberUnitId: 5,
      isManager: false,
    ),
  ];

  static List<ServicoModel> servicosList = [
    ServicoModel(
      idServico: '1',
      nome: 'Corte de Cabelo',
      urlImagem: 'assets/images/corte_cabelo.png',
      valor: 30.0,
      comissao: 10.0,
      descricao: 'Super Corte de Cabelo',
    ),
    ServicoModel(
      idServico: '2',
      nome: 'Barba',
      urlImagem: 'assets/images/barba.png',
      valor: 20.0,
      comissao: 5.0,
      descricao: 'Super Corte de Barba',
    ),
    ServicoModel(
      idServico: '3',
      nome: 'Manicure',
      urlImagem: 'assets/images/manicure.png',
      valor: 25.0,
      comissao: 8.0,
      descricao: 'Super Corte de Unha',
    ),
    ServicoModel(
      idServico: '4',
      nome: 'Pedicure',
      urlImagem: 'assets/images/pedicure.png',
      valor: 28.0,
      comissao: 9.0,
    ),
    ServicoModel(
      idServico: '5',
      nome: 'Coloração',
      urlImagem: 'assets/images/coloracao.png',
      valor: 45.0,
      comissao: 15.0,
    ),
  ];
}
